import type { Metadata } from 'next'
import './globals.css'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import { CounterStoreProvider } from '@/providers/CounterStoreProvider'
import localFont from 'next/font/local'

const Pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--typography-primitive-font-family-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${Pretendard.className}`}>
        <ReactQueryProvider>
          <CounterStoreProvider>{children}</CounterStoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
